### ISSUE TITLE
Instructions to compile are missing

### ISSUE THREAD

**Issue by neuromancer** [VenKamikaze/BitRiot#1]
Hi,

I was wondering how to compile this game in Linux. Can you provide a Makefile or some instructions in the README?

Thanks!

**Comment by VenKamikaze** [comment]
My bad. The makefile was under a Debug directory which I hadn't included. I'll push it up soon.

**Comment by neuromancer** [comment]
Thanks!, in any case, i managed to compile it because i wanted to test the
game. It looks nice indeed!.

2016-04-23 13:12 GMT+02:00 VenKamikaze notifications@github.com:

**Comment by VenKamikaze** [comment]
It's a fun game. I only ported it though so cannot take the credit :)
Glad you got it working. 

I've pushed up a makefile in case others try compiling it later :)
