### ISSUE TITLE
Code is terribly formatted

### ISSUE THREAD

**Issue by VenKamikaze** [VenKamikaze/BitRiot#10]
There's a mixture of whitespace & tabs, CRLFs and LFs all throughout the code.

I plan to format this to be all whitespace, probably 2 whitespace per indent and to remove all CRs from line endings.

**Comment by ghost** [comment]
I opened a PR that converts line endings to Unix in the sdl2_ongoing branch.

For formating the indentation I found this nice tool http://astyle.sourceforge.net/
I was a bit sceptical about it but it seems to work fine. (tested it on some files)

To format a file to 2 whitespaces per indent all you have to do is

`astyle --indent=spaces=2 example.cpp`

The original file is saved as example.cpp.orig

**Comment by VenKamikaze** [comment]
Cheers, I added a bash script under src/format-code.bash using this tool and put the options that I think work well. I have also formatted all the code under src/ using it in the sdl2_ongoing branch.

It should help in keeping the code consistent. Let me know if you want to change any aspects of the configuration/formatting.
