### ISSUE TITLE
Segfault in long lived game

### ISSUE THREAD

**Issue by VenKamikaze** [VenKamikaze/BitRiot#19]
Was testing out the controller support (PR #18) with two players (thanks LukePH!) and I'm getting occasional segfaults on long lived games (occurred in 2/4 games after about 5 minutes)

I'm not sure the cause yet, but suspect it's something to do with the input handling. Probably an existing bug that's only being exposed now that I'm testing with >1 player.

**Comment by LukePH** [comment]
I haven't seen the crash happen myself by seems d8c9893 may fix this.

**Comment by VenKamikaze** [comment]
Played a couple of games after the above patch and was unable to reproduce the crash.
Marking as resolved.

Thanks!
